"""
Database Schema for Unified System
===================================

This schema supports TRUE integration:
- Java writes transactions, Python enriches them
- Python writes profiles, Java reads them
- LLM writes document evidence, all systems use it

Add this to BankFraudTest/src/main/resources/db/migration/
"""

-- V6__unified_intelligence_schema.sql

-- Enhanced customer profiles table
-- Columns populated by DIFFERENT systems:
CREATE TABLE IF NOT EXISTS customer_profiles (
    customer_id VARCHAR(50) PRIMARY KEY,
    
    -- Traditional banking data (Java source)
    account_open_date TIMESTAMP,
    account_type VARCHAR(50),
    credit_limit DECIMAL(15,2),
    
    -- Statistical features (Java/Scala computed)
    avg_transaction_amount DECIMAL(15,2),
    transaction_count_30d INTEGER,
    max_transaction_amount DECIMAL(15,2),
    
    -- ML-derived features (Python source)
    behavior_cluster INTEGER,
    anomaly_score DECIMAL(5,4),
    spending_pattern VARCHAR(50),
    
    -- LLM-extracted features (document intelligence)
    occupation VARCHAR(100),
    income_bracket VARCHAR(50),
    risk_tolerance VARCHAR(20),
    expected_transaction_types JSONB,
    kyc_summary TEXT,
    
    -- Unified assessment
    unified_risk_score DECIMAL(5,4),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT check_risk_score CHECK (unified_risk_score BETWEEN 0 AND 1)
);

CREATE INDEX idx_customer_profiles_risk ON customer_profiles(unified_risk_score DESC);


-- Enhanced fraud alerts table
-- Tracks multi-system detection
CREATE TABLE IF NOT EXISTS fraud_alerts (
    alert_id VARCHAR(100) PRIMARY KEY,
    transaction_id VARCHAR(100) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    
    -- Scores from different detection methods
    rule_based_score DECIMAL(5,4),
    ml_model_score DECIMAL(5,4),
    llm_risk_score DECIMAL(5,4),
    
    -- Final ensemble score
    final_risk_score DECIMAL(5,4) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    detection_method VARCHAR(50) NOT NULL,
    
    -- Rich context
    rules_triggered JSONB,
    ml_features JSONB,
    llm_reasoning TEXT,
    
    -- Workflow
    status VARCHAR(50) DEFAULT 'PENDING',
    assigned_to VARCHAR(100),
    resolution_notes TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id),
    FOREIGN KEY (customer_id) REFERENCES customer_profiles(customer_id)
);

CREATE INDEX idx_fraud_alerts_customer ON fraud_alerts(customer_id);
CREATE INDEX idx_fraud_alerts_risk ON fraud_alerts(risk_level, final_risk_score DESC);
CREATE INDEX idx_fraud_alerts_method ON fraud_alerts(detection_method);
CREATE INDEX idx_fraud_alerts_status ON fraud_alerts(status);


-- Document evidence table
-- Links unstructured docs to structured transactions
CREATE TABLE IF NOT EXISTS document_evidence (
    evidence_id VARCHAR(100) PRIMARY KEY,
    alert_id VARCHAR(100),
    transaction_id VARCHAR(100) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    
    -- Document metadata
    document_source VARCHAR(200),
    document_type VARCHAR(100),
    document_path VARCHAR(500),
    
    -- LLM processing results
    extracted_text TEXT,
    key_entities JSONB,
    sentiment VARCHAR(20),
    risk_indicators JSONB,
    
    -- Linking metadata
    relevance_score DECIMAL(5,4),
    llm_reasoning TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (alert_id) REFERENCES fraud_alerts(alert_id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id)
);

CREATE INDEX idx_document_evidence_alert ON document_evidence(alert_id);
CREATE INDEX idx_document_evidence_customer ON document_evidence(customer_id);
CREATE INDEX idx_document_evidence_relevance ON document_evidence(relevance_score DESC);


-- Compliance reports table
-- Generated by LLM using data from Java DB
CREATE TABLE IF NOT EXISTS compliance_reports (
    report_id VARCHAR(100) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    report_type VARCHAR(50) NOT NULL,
    
    -- Source data metrics
    transaction_count INTEGER,
    total_suspicious_amount DECIMAL(15,2),
    
    -- LLM-generated content
    executive_summary TEXT,
    detailed_analysis TEXT,
    recommended_action TEXT,
    regulatory_citations JSONB,
    
    -- Metadata
    generated_by VARCHAR(100) DEFAULT 'UNIFIED_SYSTEM',
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(100),
    filed_at TIMESTAMP,
    
    FOREIGN KEY (customer_id) REFERENCES customer_profiles(customer_id)
);

CREATE INDEX idx_compliance_reports_customer ON compliance_reports(customer_id);
CREATE INDEX idx_compliance_reports_type ON compliance_reports(report_type);
CREATE INDEX idx_compliance_reports_status ON compliance_reports(approved_by, filed_at);


-- Investigation workflow tracking
CREATE TABLE IF NOT EXISTS investigation_workflows (
    workflow_id VARCHAR(100) PRIMARY KEY,
    alert_id VARCHAR(100) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    
    steps JSONB,
    current_step INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'IN_PROGRESS',
    
    investigation_findings JSONB,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    
    FOREIGN KEY (alert_id) REFERENCES fraud_alerts(alert_id)
);

CREATE INDEX idx_investigation_workflows_alert ON investigation_workflows(alert_id);
CREATE INDEX idx_investigation_workflows_status ON investigation_workflows(status);


-- View: Unified intelligence dashboard
-- Combines data from all systems for Java dashboard
CREATE OR REPLACE VIEW unified_intelligence_view AS
SELECT 
    fa.alert_id,
    fa.transaction_id,
    t.amount,
    t.merchant_name,
    t.transaction_date,
    fa.customer_id,
    cp.occupation,
    cp.unified_risk_score as customer_risk,
    fa.rule_based_score,
    fa.ml_model_score,
    fa.llm_risk_score,
    fa.final_risk_score,
    fa.risk_level,
    fa.detection_method,
    fa.llm_reasoning,
    COUNT(de.evidence_id) as document_count,
    fa.status,
    fa.created_at
FROM fraud_alerts fa
JOIN transactions t ON fa.transaction_id = t.transaction_id
LEFT JOIN customer_profiles cp ON fa.customer_id = cp.customer_id
LEFT JOIN document_evidence de ON fa.alert_id = de.alert_id
GROUP BY 
    fa.alert_id, fa.transaction_id, t.amount, t.merchant_name, 
    t.transaction_date, fa.customer_id, cp.occupation, cp.unified_risk_score,
    fa.rule_based_score, fa.ml_model_score, fa.llm_risk_score,
    fa.final_risk_score, fa.risk_level, fa.detection_method,
    fa.llm_reasoning, fa.status, fa.created_at
ORDER BY fa.created_at DESC;


-- Function: Calculate ensemble fraud score
-- Shows business logic in database layer
CREATE OR REPLACE FUNCTION calculate_ensemble_score(
    rule_score DECIMAL,
    ml_score DECIMAL,
    llm_score DECIMAL
) RETURNS DECIMAL AS $$
BEGIN
    -- Weighted ensemble: Rules 40%, ML 30%, LLM 30%
    RETURN (
        COALESCE(rule_score, 0.0) * 0.4 +
        COALESCE(ml_score, 0.0) * 0.3 +
        COALESCE(llm_score, 0.0) * 0.3
    );
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- Trigger: Auto-update customer profile stats
-- Java writes transactions, trigger updates Python-readable stats
CREATE OR REPLACE FUNCTION update_customer_stats()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO customer_profiles (
        customer_id, 
        avg_transaction_amount,
        transaction_count_30d,
        max_transaction_amount,
        last_updated
    )
    SELECT 
        NEW.customer_id,
        AVG(amount),
        COUNT(*),
        MAX(amount),
        CURRENT_TIMESTAMP
    FROM transactions
    WHERE customer_id = NEW.customer_id
      AND transaction_date >= CURRENT_TIMESTAMP - INTERVAL '30 days'
    ON CONFLICT (customer_id) DO UPDATE SET
        avg_transaction_amount = EXCLUDED.avg_transaction_amount,
        transaction_count_30d = EXCLUDED.transaction_count_30d,
        max_transaction_amount = EXCLUDED.max_transaction_amount,
        last_updated = EXCLUDED.last_updated;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_customer_stats
AFTER INSERT ON transactions
FOR EACH ROW
EXECUTE FUNCTION update_customer_stats();


-- Comments documenting integration
COMMENT ON TABLE customer_profiles IS 'Unified customer profile: Java stats + Python ML + LLM extraction';
COMMENT ON TABLE fraud_alerts IS 'Multi-system fraud detection: Rules + ML + LLM ensemble';
COMMENT ON TABLE document_evidence IS 'RAG-retrieved documents linked to transactions';
COMMENT ON TABLE compliance_reports IS 'LLM-generated reports using Java DB data';

COMMENT ON COLUMN customer_profiles.avg_transaction_amount IS 'Java computed';
COMMENT ON COLUMN customer_profiles.behavior_cluster IS 'Python ML computed';
COMMENT ON COLUMN customer_profiles.occupation IS 'LLM extracted from documents';
COMMENT ON COLUMN customer_profiles.unified_risk_score IS 'Combined from all sources';
